---
apiVersion: v1
kind: Service
metadata:
  name: oidc-auth
spec:
  type: ClusterIP
  selector:
    app: oidc-auth
  ports:
  - port: 8080
    name: http-oidc-auth
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oidc-auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oidc-auth
    spec:
      volumes:
      - name: oidc-config
        secret:
          secretName: oidc-config
      containers:
      - name: oidc-auth
        image: dgaffuri/ambassador-auth-oidc:0.12
        imagePullPolicy: Never
        ports:
        - name: http-api
          containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: CONFIG_FILE
            value: "/etc/oidc-auth/oidc-config.json"
        volumeMounts:
        - name: oidc-config
          mountPath: "/etc/oidc-auth"
          readOnly: true
